function populateSpaceAndPlot(prepopulatedSpaceFile)

% Takes a matlab data file generated by the logging system (createLog), loads it and 
% uses the plotting functions to regenerate the plot. Basic images are generated for the
% figures.
 
% Inputs:
%   prepopulatedSpaceFile: File to load the varaible data space from.
%   plotGoalFlag: If false then the goal values are not added to the plot.

% TODO:
%   - Add figures for the alignment phase.

plotIter = 1;
plotGoalFlag = 0;

space = getPrepopulatedSpaceFrom(prepopulatedSpaceFile);

for count = 1:1:space.ii
    plotModels(plotIter, plotGoalFlag, count, space.Rci, space.Rfi, space.Rsi, ...
            space.Rsai, space.OPTopts);
    print(['plotModel_', mat2str(count) ], '-depsc')
end

plotNormalised = 1;
plotIterations(plotIter, space.xi, space.Ti.Delta, space.OPTopts, space.SMopts, ...
        space.Si, plotNormalised, 'Normalised');
print(['plotIteration_normalised', mat2str(count) ], '-depsc')
plotIterations(plotIter, space.xi, space.Ti.Delta, space.OPTopts, space.SMopts, space.Si, ...
         ~plotNormalised, 'De-normalised/globalised/universalised');
print(['plotIteration_deNormalised', mat2str(count) ], '-depsc')

end % populateSpaceAndPlot